[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["NODE_ENV=development npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node server.cjs"

[variables]
NODE_ENV = "production"
PORT = "3000"


