[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["env NODE_ENV=development NPM_CONFIG_PRODUCTION=false npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node server.cjs"

[variables]
NPM_CONFIG_PRODUCTION = "false"
PORT = "3000"


